modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory (30 is current forge version)
issueTrackerURL="https://github.com/Kashdeya/Tiny-Progressions/issues" #optional
license = "ARR"
[[mods]] #mandatory
modId="tp" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Tiny Progressions" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/tiny-progressions" #optional
logoFile="tplogo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Kashdeya, Darkosto, GenDeathrow, ArclightTW, Vadis365" #optional
description='''
Cobblegens, Growth Crystals and Watering Cans and more oh my!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tp]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.tp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
